name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out Looker Actions 🚀
on: [push]
env:
  BASE_URL: https://gcpl236.cloud.looker.com
  LOOKER_CLIENT_ID: XV54MFwzKgDzBKsPh7Db
  LOOKER_SECRET: NcJPGjm5vSn9bN7pgwXTPHgR
jobs:
  looker-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check target branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Create config file
        shell: bash
        run: |
          echo [looker] > looker.ini
          echo "base_url=${{env.BASE_URL}}" >> looker.ini
          echo "client_id=${{env.LOOKER_CLIENT_ID}}" >> looker.ini
          echo "client_secret=${{env.LOOKER_SECRET}}" >> looker.ini
          echo "verify_ssl=True" >> looker.ini
          
      - name: Install Looker SDK
        run: pip install looker_sdk
      
      - name: Run script
        run: python .github/workflows/hello_looker.py
